OnlineStore/Models/Product.cs
using OnlineStore.Areas.Identity.Data;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Configuration;
using System.Diagnostics.CodeAnalysis;

namespace OnlineStore.Models
{
    public class Product
    {
        [Key]
        public int Id { get; set; }

        [MaxLength(50)]
        [Required]
        public string Name { get; set; }

        [MaxLength(100)]
        [Required]
        public string Description { get; set; }
        [Required]
        public double UnitPrice { get; set; }
        [Required]
        [Range(0,90,ErrorMessage ="Discount must be between ( 0%, 90% )")]
        public int Discount { get; set; }
        [AllowNull]
        public byte[]? Image { get; set; }
        [Required]
        [Range(1,10000,ErrorMessage ="Quantity must be at least 1") ]
        public int Quantity { get; set; }

        [MaxLength(50)]
        [Required]
        public string Category { get; set; }

        [ForeignKey("Seller")]
        public string SellerId { get; set; }

    }
}

OnlineStore/Controllers/CartController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using OnlineStore.Areas.Identity.Data;
using OnlineStore.Data;
using OnlineStore.Models;

namespace OnlineStore.Controllers
{
    public class CartController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly UserManager<AppUser> _userManager;
        private readonly StoreDbContext db;
        public CartController(ILogger<HomeController> logger, UserManager<AppUser> userManager, StoreDbContext _db)
        {
            _logger = logger;
            _userManager = userManager;
            db = _db;
        }
        public IActionResult Index()
        {
            var user = _userManager.GetUserId(this.User);
            foreach (var us in db.Users)
            {
                if (us.Id == user)
                {
                    ViewBag.FirstName = us.FirstName;
                    ViewBag.LastName = us.LastName;
                    ViewBag.Id = us.Id;
                }
            }
            var items = db.Carts.Where(c => c.UserId == user).ToList();
            if (items.Count == 0)
            {
                return RedirectToAction("EmptyCart");
            }
            Dictionary<KeyValuePair<string,string>, KeyValuePair<int, double>> temp = new Dictionary<KeyValuePair<string, string>, KeyValuePair<int, double>>();
            double totalSum = 0.0;
            foreach (var item in items)
            {
                var prod = db.Products.Find(item.ProductId);
                double price = prod.UnitPrice - (prod.UnitPrice * (prod.Discount * 1.0 / 100));
                totalSum += price * item.Quantity;

                temp.Add(new KeyValuePair<string, string>(prod.Name, item.SellerId), new KeyValuePair<int, double>(item.Quantity, price * item.Quantity));
            }
            ViewBag.Sum = totalSum;
            return View(temp);

        }
        public IActionResult Add(int id, int RequiredQuantity, string SellerId)
        {
            var pro = db.Products.Find(id);
            var user = _userManager.GetUserId(this.User);
            var cart = db.Carts.FirstOrDefault(c => c.UserId == user && c.ProductId == id && c.SellerId == SellerId);
            if (cart == null)
            {
                cart = new Cart()
                {
                    ProductId = id,
                    UserId = user,
                    Quantity = RequiredQuantity,
                    SellerId = SellerId
                };
                db.Carts.Add(cart);
            }
            else
            {
                cart.Quantity += RequiredQuantity;
                db.Update(cart);
            }
            pro.Quantity -= RequiredQuantity;
            db.Update(pro);
            db.SaveChanges();
            return View();

        }
        public IActionResult Confirm(string Id)
        {
            var items = db.Carts.Where(c => c.UserId == Id);
            foreach (var item in items)
            {
                db.Carts.Remove(item);
            }
            db.SaveChanges();
            return View();

        }
        public IActionResult Cancel(string Id)
        {
            var items = db.Carts.Where(c => c.UserId == Id);
            foreach (var item in items)
            {
                var prod = db.Products.FirstOrDefault(c => c.Id == item.ProductId);
                prod.Quantity += item.Quantity;
                db.Update(prod);
                db.Carts.Remove(item);
            }
            db.SaveChanges();
            return View();
        }
        public IActionResult EmptyCart()
        {
            return View();
        }

    }
}

OnlineStore/Controllers/ProductController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using OnlineStore.Areas.Identity.Data;
using OnlineStore.Data;
using OnlineStore.Data.Enums;
using OnlineStore.Models;
using System.Diagnostics;

namespace OnlineStore.Controllers
{
    public class ProductController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly UserManager<AppUser> _userManager;
        private readonly StoreDbContext db;
        public ProductController(ILogger<HomeController> logger, UserManager<AppUser> userManager, StoreDbContext _db)
        {
            _logger = logger;
            _userManager = userManager;
            db = _db;
        }
        public IActionResult Index()
        {
            var user = _userManager.GetUserId(this.User);
            foreach (var us in db.Users)
            {
                if (us.Id == user)
                {
                    ViewBag.Name = us.FirstName;
                    ViewBag.Type = us.UserType;
                    ViewBag.Id = us.Id;
                }
            }

            return View(db.Products.ToList());
        }

        public IActionResult New()
        {
            var user = _userManager.GetUserId(this.User);
            foreach (var us in db.Users)
            {
                if (us.Id == user)
                {
                    ViewBag.ID = us.Id;
                    ViewBag.Type = us.UserType;
                }
            }
            if (ViewBag.Type == UserType.Seller)
                return View();
            else
                return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult New(Product p, IFormFile? Imagefile)
        {
            if (ModelState.IsValid)
            {
                if (Imagefile != null)
                {
                    var memStream = new MemoryStream();
                    Imagefile.CopyTo(memStream);
                    p.Image = memStream.ToArray();
                }
                db.Products.Add(p);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            var user = _userManager.GetUserId(this.User);
            foreach (var us in db.Users)
            {
                if (us.Id == user)
                {
                    ViewBag.ID = us.Id;
                }
            }
            return View("New", p);
        }

        public IActionResult Details(int id)
        {
            var user = _userManager.GetUserId(this.User);
            var pro = db.Products.Find(id);
            foreach (var us in db.Users)
            {
                if (us.Id == pro.SellerId)
                {
                    ViewBag.FirstName = us.FirstName;
                    ViewBag.LastName = us.LastName;
                    ViewBag.SellerId = us.Id;
                    
                }
                if (us.Id == user)
                {
                    ViewBag.Id = us.Id;
                    ViewBag.Type = us.UserType;
                }
            }
            return View(pro);
        }

        public IActionResult Edit(int id)
        {
            var user = _userManager.GetUserId(this.User);
            var prod = db.Products.FirstOrDefault(p => p.Id == id);
            foreach (var us in db.Users)
            {
                if (prod.SellerId == us.Id)
                {
                    ViewBag.FirstName = us.FirstName;
                    ViewBag.LastName = us.LastName;
                    ViewBag.Id = us.Id;
                }
            }
            if (ViewBag.Id == user)
                return View(db.Products.Find(id));
            else
                return RedirectToAction("Index");

        }

        [HttpPost]
        public IActionResult Edit(Product newPro, IFormFile? Imagefile)
        {
            try
            {
                if (newPro.Id != 0)
                {
                    if (ModelState.IsValid)
                    {
                        var existingPro = db.Products.Find(newPro.Id);
                        if (Imagefile != null)
                        {
                            var memStream = new MemoryStream();
                            Imagefile.CopyTo(memStream);
                            newPro.Image = memStream.ToArray();
                        }
                        else
                        {
                            newPro.Image = existingPro.Image;
                        }
                        existingPro.Name = newPro.Name;
                        existingPro.UnitPrice = newPro.UnitPrice;
                        existingPro.Quantity = newPro.Quantity;
                        existingPro.Description = newPro.Description;
                        existingPro.Discount = newPro.Discount;
                        existingPro.Category = newPro.Category;
                        existingPro.Image = newPro.Image;

                        db.Update(existingPro);
                        db.SaveChanges();
                        return RedirectToAction("Index");
                    }
                }
                return RedirectToAction("Edit", newPro);
            }
            catch (Exception ex)
            {
                return RedirectToAction("Edit", newPro);
            }
        }

        public IActionResult Delete(int id)
        {
            var user = _userManager.GetUserId(this.User);
            var prod = db.Products.FirstOrDefault(p => p.Id == id);
            foreach (var us in db.Users)
            {
                if (us.Id == prod.SellerId)
                {
                    ViewBag.Id = us.Id;
                    ViewBag.FirstName = us.FirstName;
                    ViewBag.LastName = us.LastName;
                    ViewBag.Id = us.Id;
                }
            }
            if (ViewBag.Id == user)
                return View(db.Products.Find(id));
            else
                return RedirectToAction("Index");

        }

        [HttpPost]
        public IActionResult Delete(Product p, int Id)
        {
            try
            {
                Product pro = db.Products.Find(Id);
                db.Remove(pro);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                return RedirectToAction("Index");
            }
        }

        public IActionResult SellerProducts(string Id)
        {
            var items = db.Products.Where(p => p.SellerId == Id).ToList();
            var user = _userManager.GetUserId(this.User);
            foreach (var us in db.Users)
            {
                if (us.Id == Id)
                {
                    ViewBag.FirstName = us.FirstName;
                    ViewBag.LastName = us.LastName;
                }
                if(us.Id == user)
                {
                    ViewBag.Id = us.Id;
                }
            }
            return View(items);
        }
        public IActionResult Search(string? query)
        {
            var user = _userManager.GetUserId(this.User);
            foreach (var us in db.Users)
            {
                if (us.Id == user)
                {
                    ViewBag.Name = us.FirstName;
                    ViewBag.Type = us.UserType;
                    ViewBag.Id = us.Id;
                }
            }
            var items = new List<Product>();
            if (query == null)
                items = db.Products.ToList();
            else
            {
                items = db.Products.Where(p => p.Name.ToLower().Contains(query.ToLower()) || p.Description.ToLower().Contains(query.ToLower()) || p.Category.ToLower().Contains(query.ToLower())).ToList();
                if (items.Count == 0) 
                {
                    return View("NotFound");
                }
            }
            return View("Index", items);
        }
    }
}

OnlineStore/Controllers/UserController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using OnlineStore.Areas.Identity.Data;
using OnlineStore.Data;

namespace OnlineStore.Controllers
{
    public class UserController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly UserManager<AppUser> _userManager;
        private readonly StoreDbContext db;
        public UserController(ILogger<HomeController> logger, UserManager<AppUser> userManager, StoreDbContext _db)
        {
            _logger = logger;
            _userManager = userManager;
            db = _db;
        }

        public IActionResult ManageProduct(string Id)
        {
            var products = db.Products.Where(p => p.SellerId == Id).ToList();

            foreach (var us in db.Users)
            {
                if (us.Id == Id)
                {
                    ViewBag.FirstName = us.FirstName;
                    ViewBag.LastName = us.LastName;
                }
            }

            return View(products);
        }
    }
}

OnlineStore/Views/Product/Delete.cshtml
@model Product
@using OnlineStore.Data.Enums;
@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>
<form method="post" asp-action="Delete" asp-controller="Product" asp-route-Id="@Model.Id">
    <partial name="_DetailsPartial" model="Model" view-data="ViewData" />
    <div class="col-lg-12">
        <h6>Quantity Available : @Model.Quantity</h6>
    </div>
    <div class="col-lg-12 mt-3">
        <div class="row">
            <div class="col-lg-6 pb-2">
                <input type="submit" value="Delete" class="btn btn-danger w-100" />
            </div>
            <div class="col-lg-6">

                <a asp-action="ManageProduct" asp-controller="User" asp-route-Id="@ViewBag.Id" class="btn btn-success w-20">Back To My Products</a>

            </div>
        </div>
    </div>
    </div>
    </div>
    </div>
    </div>
    </div>
    </div>
</form>

OnlineStore/Views/Product/Details.cshtml
@model Product
@using OnlineStore.Data.Enums;
@{
    ViewData["Title"] = "Details";
}
<form method="post" asp-controller="Cart" asp-action="Add" asp-route-Id="@Model.Id" asp-route-SellerId="@Model.SellerId">
    <partial name="_DetailsPartial" model="Model" view-data="ViewData" />
    <div class="col-lg-12">
        <h6>Quantity Available : @Model.Quantity</h6>
        @if (ViewBag.Id != Model.SellerId)
        {
            <label class="form-label">Required Quantity: </label>
            <input type="number" name="RequiredQuantity" class="form-control text-center w-100" value="1" min="1" max="@Model.Quantity">
        }
    </div>
    <div class="col-lg-12 mt-3">
        @if (ViewBag.Id == null)
        {
            <a href="/identity/account/login" class="btn btn-danger w-100">Add to Cart</a>
        }
        else
        {
            @if (Model.Quantity > 0 && ViewBag.Id != Model.SellerId)
            {
                <div class="row">
                    <button type="submit" class="btn btn-danger w-100">Add To Cart</button>
                </div>
            }
        }
    </div>
    </div>
    </div>
    </div>
    </div>
    </div>
    </div>
</form>

OnlineStore/Views/Product/Edit.cshtml
@model Product


@{
    ViewData["Title"] = "Edit";
   
}
<h1>Edit</h1>


<form method="post" enctype="multipart/form-data" asp-action="edit" asp-controller="product" asp-route-Id="@Model?.Id">
    <partial name="_FormPartial" model="Model" view-data="ViewData" />

    <div class="mb-3">
        <label class="form-label">Image</label>
        <div class="custom-file">
            @{
                string? imgsrc = null;
                if (@Model.Image != null)
                {
                    string base64String = Convert.ToBase64String(@Model?.Image);
                    imgsrc = $"data:image/jpeg;base64,{base64String}";
                    <img src="@imgsrc" height="400" width="200" class="border p-3">
                }
                else
                {
                    <img class="border p-3" width="300" height="400" src="/Images/images.png">
                }
            }
            <label class="custom-file-label" for="customFile">Choose Image</label>
            <input type="file" name="Imagefile" class="custom-file-input"/>

        </div>
    </div>


    <br />
    <button type="submit" class="btn btn-outline-primary">Submit</button>
   
    <a asp-action="ManageProduct" asp-controller="User" asp-route-Id="@ViewBag.Id" class="btn btn-success w-20">Back To My Products</a>
    
</form>
@section scripts{

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
}

OnlineStore/Views/Product/Index.cshtml
@model List<Product>
@{
    ViewData["Title"] = "Index";
}
<div class="container">
    <div class="row">
        @foreach (var item in Model)
        {
            if (item.Quantity > 0)
            {
                <div class="col-12 col-sm-8 col-md-6 col-lg-4">
                    <div class="card">
                        @{
                            string? imgsrc = null;
                            if (@item.Image != null)
                            {
                                string base64String = Convert.ToBase64String(@item?.Image);
                                imgsrc = $"data:image/jpeg;base64,{base64String}";
                                <img class="card-img" width="200" height="400" src=@imgsrc alt="@item.Name">
                            }
                            else
                            {
                                <img class="card-img" width="200" height="400" src="/Images/images.png" alt="@item.Name">
                            }
                        }
                        <div class="card-body">
                            <h4 class="card-title">@item.Name</h4>
                            <h6 class="card-subtitle mb-2 text-muted">Category: @item.Category</h6>
                            <p class="card-text">
                                @item.Description
                            </p>
                            <div class="buy d-flex justify-content-between align-items-center">
                                @if (item.Discount > 0)
                                {
                                    double newPrice = item.UnitPrice - (item.UnitPrice * (item.Discount * 1.0 / 100));
                                    <div class="price text-success">
                                        <h5 class="mt-4">
                                            <sub>-@item.Discount%</sub>
                                            $@newPrice.ToString()
                                        </h5>
                                    </div>
                                }
                                else
                                {
                                    <div class="price text-success"><h5 class="mt-4">$@item.UnitPrice</h5></div>
                                }
                                @if(ViewBag.Id == null)
                                {
                                    <a href="/identity/account/login" class="btn btn-danger w-20">Add to Cart</a>
                                }
                                else
                                {
                                    @if (ViewBag.Id != item.SellerId)
                                    {
                                        <a asp-controller="Cart" asp-action="Add" asp-route-Id="@item.Id" asp-route-SellerId="@item.SellerId" asp-route-RequiredQuantity="1" class="btn btn-danger w-20">Add to Cart</a>
                                    }
                                }
                                
                                <a asp-action="Details" asp-route-Id="@item.Id" class="btn btn-success w-20">Details</a>
                            </div>
                        </div>
                    </div>
                </div>
            }
        }
    </div>
</div>

OnlineStore/Views/Product/New.cshtml
@model Product
@{
    ViewData["Title"] = "New";

}

<h1>New</h1>
<form method="post" enctype="multipart/form-data" asp-action="New" asp-controller="product">
    <partial name="_FormPartial" model="Model" view-data="ViewData" />

    <div class="mb-3">
       
        <div class="custom-file">
            <label class="custom-file-label" for="customFile">Choose Image</label>
            <input type="file" name="Imagefile" class="custom-file-input" id="customFile" />
        </div>
    </div>


    <br />
    <button type="submit" class="btn btn-outline-primary">Submit</button>
</form>
@section scripts{

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
}

OnlineStore/Views/Product/NotFound.cshtml
@{
    ViewData["Title"] = "NotFound";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container">

        <h1 style="text-align:center; color:red"> Not Found !!!</h1>
   

    <a asp-action="Index" asp-controller="Product" asp-route-Id="" class="alert-link">Back to Products</a>
</div>

OnlineStore/Views/Product/SellerProducts.cshtml
@model List<Product>
@{
    ViewData["Title"] = "SellerProducts";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>@ViewBag.FirstName @ViewBag.LastName Products</h1>

<div class="container">
    <div class="row">
        @foreach (var item in Model)
        {
            if (item.Quantity > 0)
            {
                <div class="col-12 col-sm-8 col-md-6 col-lg-4">
                    <div class="card">
                        @{
                            string? imgsrc = null;
                            if (@item.Image != null)
                            {
                                string base64String = Convert.ToBase64String(@item?.Image);
                                imgsrc = $"data:image/jpeg;base64,{base64String}";
                                <img class="card-img" width="200" height="400" src=@imgsrc alt="@item.Name">
                            }
                            else
                            {
                                <img class="card-img" width="200" height="400" src="/Images/images.png" alt="@item.Name">
                            }
                        }
                        <div class="card-body">
                            <h4 class="card-title">@item.Name</h4>
                            <h6 class="card-subtitle mb-2 text-muted">Category: @item.Category</h6>
                            <p class="card-text">
                                @item.Description
                            </p>
                            <div class="buy d-flex justify-content-between align-items-center">
                                @if (item.Discount > 0)
                                {
                                    double newPrice = item.UnitPrice - (item.UnitPrice * (item.Discount * 1.0 / 100));
                                    <div class="price text-success">
                                        <h5 class="mt-4">
                                            <sub>-@item.Discount%</sub>
                                            $@newPrice.ToString()
                                        </h5>
                                    </div>
                                }
                                else
                                {
                                    <div class="price text-success"><h5 class="mt-4">$@item.UnitPrice</h5></div>
                                }
                                @if (ViewBag.Id == null)
                                {
                                    <a href="/identity/account/login" class="btn btn-danger w-20">Add to Cart</a>
                                }
                                else
                                {
                                    @if (ViewBag.Id != item.SellerId)
                                    {
                                        <a asp-controller="Cart" asp-action="Add" asp-route-Id="@item.Id" asp-route-SellerId="@item.SellerId" asp-route-RequiredQuantity="1" class="btn btn-danger w-20">Add to Cart</a>
                                    }
                                }
                                <a asp-action="Details" asp-route-Id="@item.Id" class="btn btn-success w-20">Details</a>
                            </div>
                        </div>
                    </div>
                </div>
            }
        }
    </div>
</div>

OnlineStore/Views/Product/_DetailsPartial.cshtml
@model Product
@using OnlineStore.Data.Enums;

<div class="container">
    <div class="col-lg-8 border p-3 main-section bg-white">
        <div class="row m-0">
            <div class="col-lg-4 left-side-product-box pb-3">
                @{
                    string? imgsrc = null;
                    if (Model.Image != null)
                    {
                        string base64String = Convert.ToBase64String(@Model?.Image);
                        imgsrc = $"data:image/jpeg;base64,{base64String}";
                        <img class="border p-3" width="300" height="416" src=@imgsrc alt="@Model.Name">
                    }
                    else
                    {
                        <img class="border p-3" width="300" height="416" src="/Images/images.png" alt="@Model.Name">
                    }
                }
            </div>
            <div class="col-lg-8">
                <div class="right-side-pro-detail border p-3 m-0">
                    <div class="row">
                        <div class="col-lg-12">
                            <span>@Model.Category</span>
                            <p class="m-0 p-0">@Model.Name</p>
                        </div>
                        <div class="col-lg-12">
                            @if (Model.Discount > 0)
                            {
                                double newPrice = Model.UnitPrice - (Model.UnitPrice * (Model.Discount * 1.0 / 100));
                                <p class="m-0 p-0 price-pro">$@newPrice</p>
                            }
                            else
                            {
                                <p class="m-0 p-0 price-pro">$@Model.UnitPrice</p>
                            }
                            <hr class="p-0 m-0">
                        </div>
                        <div class="col-lg-12 pt-2">
                            <h5>Product Detail</h5>
                            <span>@Model.Description</span>
                            <hr class="m-0 pt-2 mt-2">
                        </div>
                        <div class="col-lg-12">
                            <p class="tag-section"><strong>Seller : </strong><a asp-action="SellerProducts" asp-route-Id="@ViewBag.SellerId">@ViewBag.FirstName @ViewBag.LastName</a></p>
                        </div>
                        
                        

OnlineStore/Views/Product/_FormPartial.cshtml
@model Product


<input asp-for="SellerId" hidden value="@ViewBag.Id" />
<div class="mb-2">
    <label asp-for="Name" class="form-label"></label>
    <input asp-for="Name" class="form-control" value="@Model?.Name">
    <span asp-validation-for="Name" class="text-danger"></span>
</div>

<div class="mb-2">
    <label asp-for="UnitPrice" class="form-label"></label>
    <input asp-for="UnitPrice" class="form-control" value="@Model?.UnitPrice">
    <span asp-validation-for="UnitPrice" class="text-danger"></span>
</div>

<div class="mb-2">
    <label asp-for="Quantity" class="form-label"></label>
    <input asp-for="Quantity" class="form-control" value="@Model?.Quantity">
    <span asp-validation-for="Quantity" class="text-danger"></span>
</div>

<div class="mb-2">
    <label asp-for="Description" class="form-label"></label>
    <input asp-for="Description" class="form-control" value="@Model?.Description">
    <span asp-validation-for="Description" class="text-danger"></span>
</div>


<div class="mb-2">
    <label asp-for="Discount" class="form-label"></label>
    <input asp-for="Discount" class="form-control" value="@Model?.Discount">
    <span asp-validation-for="Discount" class="text-danger"></span>
</div>

<div class="mb-2">
    <label asp-for="Category" class="form-label"></label>
    <input asp-for="Category" class="form-control" value="@Model?.Category">
    <span asp-validation-for="Category" class="text-danger"></span>
</div>